title: Meta-phor-us
description: A blog about code, ideas, and everything in between.
author: James Rowland
email: ""

baseurl: ""
url: "https://rowland-208.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

show_excerpts: true
